:em: {sp}--{sp}
:license-link: link:https://www.gnu.org/licenses/agpl-3.0.en.html[]
:raw-url: https://raw.githubusercontent.com/vs-123/ant/refs/heads/main
:lant: https://en.wikipedia.org/wiki/Langton's_ant

= ANT

*ant* is a multi-agent link:{lant}[Langton's Ant] simulation implemented in C99. This provides a real-time interactive environment for observing complex emergent behaviours from simple cellular automata rules.

== FEATURES

* **[DYNAMIC INTERACTION]** {em} Toggle individual ants on the board via mouse input
* **[STATE CONTROL]** {em} Pause, resume or step through the simulation frame by frame
* **[SCALABLE AGENTS]** {em} Supports up to `C - 1` number of active ants where `C` is the number of cells in the board
* **[VISIBILITY]** {em} Toggleable UI overlay is implemented to allow for a clean distraction-free viewing experience
* **[WRAP AROUND TOPOLOGY]** {em} Ants in this project navigate a toroidal grid. They transition seamlessly across board edges

== Controls

[cols="1,1",options="header"]
|===
| KEY | ACTION 
| *SPACE* | Toggle Pause/Resume 
| *N* | Step {em} Increment by one frame 
| *C* | Clear Board 
| *H* | Toggle UI Visibility 
| *MOUSE1* | Toggle ant at cursor position 
|===

== Rules

The simulation follows the standard link:{lant}[Langton's Ant] logic for each agent:

. *WHITE SQUARE* {em} Turn 90° clockwise, flip the colour of the square to black and move forward one unit.
. *BLACK SQUARE* {em} Turn 90° counter clockwise, flip the colour of the square to white and move forward one unit.

== BUILD INSTRUCTIONS

* Obtain a local copy of this repository with `git` and enter it
+
[source,]
----
  %  git clone https://github.com/vs-123/ant.git
  %  cd ant
----

* Ensure you have the following prerequisites:
** A C99-compliant C compiler
** CMake version `3.10` or higher (optional if you wish to proceed with <<manual-method, MANUAL METHOD>>)
** Raylib

=== CMAKE METHOD

* Create a `build` directory and enter it
+
[source,]
----
  %  mkdir build
  %  cd build
----

* Use CMake to build and link the project
+
[source,]
----
  %  cmake ..
  %  cmake --build .
  %  ls -Fa
  ./  ../  ant* compile_commands.json  Makefile
----

* You may now proceed with <<usage-section, USAGE>>

[[manual-method]]
=== MANUAL METHOD

* Create a `build` directory and enter it
+
[source,]
----
  %  mkdir build
  %  cd build
----

* Use the compiler of your choice to compile `src/main.c` 
+
*[NOTE]* Make sure to link `raylib` and other necessary libraries when you compile the project.
+
[source,]
----
  %  clang -o ant ../src/client.c $(pkg-config --cflags --libs raylib)
  %  ls -Fa
  ./  ../  ant*
----

* You may now proceed with <<usage-section, USAGE>>

[[usage-section]]
== USAGE

* Execute the binary
+
[source,]
----
  %  ./ant
----

== LICENSE

This project is licensed under the *GNU Affero General Public License version 3.0 or later*.

*NO WARRANTY PROVIDED*

For more information, see `LICENSE` file or visit {license-link}.
